### ISSUE TITLE
Adjust "Curlize Replacement" instructions to explicitly install wget-ssl?

### ISSUE THREAD

**Issue by getawaywithrmdir** [Lanchon/ddwrt-secure-entware#2]
I don't know if this is always how this works, but when I installed the 'full' wget via opkg after the whole curlizer symlink process and securely installing entware, it installed wget-nossl (/opt/bin/wget was symlinked to /opt/libexec/wget-nossl). When I removed it and did `opkg install wget-ssl` explicitly, it (correctly?) installed it with an /opt/bin/wget symlinked to /opt/libexec/wget-ssl.

I am far from an expert, but figured I'd share in case the instructions should be updated (just for installing 'wget-ssl' instead of the less-explicit 'wget' that ended up installing 'wget-nossl'). Unless wget-nossl is still capable of using https somehow...? Would love to understand this better 😅.

**Comment by Lanchon** [comment]
hi, thanks! you are probably right.

because of lack of freedom in ddwrt, meaning you can't do your own builds, and bad experiences with the project maintainer, i decided to get rid of all broadcom hardware and switch to openwrt and its compatible hardware. i couldn't be happier about this move and i wholeheartedly recommend it, the ROI has been immense. i am done with ddwrt for good, which is why this repo is effectively abandoned.

so i cannot tell you whether this issue has always been there or is new, more probably the former. ~if you want, you can do a PR with the needed doc changes. or~ if you are willing to maintain this repo, fork it and i'll set up a link from my repo to yours and archive my repo.

thanks for pointing this issue out!

EDIT: i made the doc changes myself. but if you are willing, we can still switch the repo maintenance.

**Comment by getawaywithrmdir** [comment]
Wow, thanks for the quick update!

I would offer my assistance, but there's a strong possibility I'm going to be changing to openwrt at some point in the next year or so myself 😅. (It's been hard to justify for a long time, since I have a broadcom SOHO from many years ago that still works pretty great and rivals most others I can get today, but I'm antsy to try out firmware with, at the very least, better documentation.)

I just figured I'd say something since it is hard to find much info on properly getting entware on dd-wrt (and this repo got me 99.99% of the way there!); I'm sure this will help other folks out there following this particular white rabbit 🙃.

**Comment by Lanchon** [comment]
ok. i'd definitely recommend the move, do it sooner rather than later.

if you want i could help you choose cheap good hardware, depending on where you live. are you in the states?

**Comment by getawaywithrmdir** [comment]
_(sorry for the delayed response)_

That's so nice of you! I am in the States. I'm tempted to just get the latest supported 'Wifi #' I can afford for longevity's sake, but would love some advice. I don't have a very big area to cover, and only 1 floor, but there's plenty of walls to penetrate and no good central location for traditional wifi coverage without rigging stuff through the ceiling (yay for Matter if the kinks get ironed out)...also preferring at least 1 USB port, ideally >=3.0, and at least the speeds we currently have with our Netgear Nighthawk R6400v2...fun times 😅. Got a bunch of IoT stuff, too. Doesn't really need to support fiber speeds since it doesn't exist in our area yet, but we're dying for it to come here.

I love this freaking router, but that dang Broadcom...😞

I'd take this to private message if GitHub had such a thing, but oh well 🤷.

**Comment by Lanchon** [comment]
i've had an exceptional experience with AC Wave2 routers based on IPQ8065.

- here is one with great coverage and speed:

https://openwrt.org/inbox/toh/askey/rt4230w_rev6
https://wikidevi.wi-cat.ru/Askey_RAC2V1K

dual core @ 1.7 GHz, 1 GB ram, 512 MB flash, 4x4 AC Wave2 5 GHz, 4x4 N 2.4 GHz. would be branded as "AC2600".

around $40, with original power brick:
https://www.ebay.com/itm/296110811990
https://www.ebay.com/itm/355747169986 (this is bidding for around $30)

problems:
1) some devices have 256 MB flash (rev 10) instead of 512 MB (rev 6). all devices with QR codes at the back are rev 10. most devices without QR codes are rev 6. rev 6 is obviously preferable.
2) some devices require opening up and connecting to its 3.3V serial port to install openwrt. this is cumbersome and may not be what you want, especially if you do not have a 3.3V TTL USB-serial adapter already. so far, all rev 6 devices i've seen could be installed without serial connection, but i've heard reports that latest firmware update plugs the hole used to avoid serial.
3) this is RAC2V1K. many sellers will sell RAC2V1A or RAC2V1S, which look the same from the outside, and pass them up for RAC2V1Ks. the model number is besides the power jack; do not buy used devices for which you can't clearly see the model number in pictures.

- another fairly used choice with same SoC is:

https://openwrt.org/toh/netgear/r7800
https://wikidevi.wi-cat.ru/Netgear_R7800

dual core @ 1.7 GHz, 512 MB ram, 128 MB flash.
that is 1/2 the ram and 1/4 or 1/2 the flash of the previous router.

around $40:
https://www.ebay.com/itm/156235831375

upside: you don't need serial to install!
downside: https://openwrt.org/toh/netgear/r7800#broken_nand_chipsblocks

i haven't used these but they are fairly used by the community.

-----

IPQ8065 is seriously performant and absolutely stable as rock. shortcomings:
- 32 bit arm arch (not 64 bit arch). if i was buying super router today, i'd aim for 64 bit.
- AC Wave2 router is not AX. does not support wifi 6E (ie, 6 GHz). for these features you'd need to choose ath11k based qualcomm device (this one is ath10k). idk how stable is ath11k, but ath10k is rock solid. you could also go for a mediatek device. mediatek AX might be more stable than qualcomm AX, idk. definitely look into mediatek if you want AX / wifi 6 / wifi 6E.

**Comment by Lanchon** [comment]
and this is cool to have...

USB 3.3V serial adapter:
- $4 from china: https://www.ebay.com/itm/126373033673
- $9 from US: https://www.ebay.com/itm/226071931646

or something like this that is multivoltage:
https://www.ebay.com/itm/166288768632

you may need something like this to connect to the board:
https://www.ebay.com/itm/394816335994

and something like this to solder to the board if your board does not come with a connector:
https://www.ebay.com/itm/404889215830

...but then you need a soldering iron, solder, etc...

btw, if you are interested in routers, being able to connect to serial ports is really valuable, so you can start on that path if you like to tinker.
